### PR TITLE
Create dedicated directory for Cadence tests

### PR DESCRIPTION
**Pull request by m-Peter**
I wanted to update the example tests in this repository, with code coverage support. However, I run into a bug that comes from how `flow test` command handles relative paths when importing contracts. For example:

```bash
flow test --cover *.cdc      
Running tests...

Test results: "intergration_test_advanced.cdc"
- PASS: testDeployingContractWithImports
Test results: "intergration_test_simple.cdc"
- PASS: testSimpleScript
- PASS: testSimpleTransaction
- PASS: testInvokingContractFunction
Test results: "unit_tests.cdc"
- FAIL: testAssertionFailure
		Execution failed:
			error: assertion failed: manually failed the test case
			  --> 7465737400000000000000000000000000000000000000000000000000000000:15:4
			
- PASS: testImportingContract
- PASS: testReadingFile
Coverage: 42.9% of statements
```

However, the following command fails spectacularly :sweat_smile: :

```bash
flow test --cover tests/*.cdc
Running tests...
❌ Command Error: Execution failed:
error: internal error: open tests/contracts/hello_contract.cdc: no such file or directory
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/onflow/cadence/runtime/errors.NewUnexpectedErrorFromCause(...)
```

### CODE REVIEW

**Comment by m-Peter** [comment]
Attempt to fix this in https://github.com/onflow/flow-cli/pull/985.

**Comment by SupunS** [comment]
Thanks for adding this!

It seems the newly added files are duplicates of existing ones (with only the paths changes). Should we maybe simply move the existing ones to the `test` directory, instead of copying them?

**Comment by m-Peter** [comment]
Yes, exactly, that is my end goal :+1: . However, I just kept the existing ones to showcase the misbehavior. I will update this :pray:

**Comment by m-Peter** [comment]
I have removed the copied Cadence test files.
I have added also the generated `coverage.json` file.
I updated the `flow.json` config file with more contracts. With regards to your [comment](https://github.com/onflow/flow-cli/pull/985#discussion_r1173060152), I was able to demonstrate the bug, when more than 1 contracts are in the config file. Kudos for finding this :clap: 
I want to update the README as well, with some instructions, however we need a `flow-cli` version that includes the aforementioned bug fix.

**Comment by m-Peter** [comment]
@SupunS I have updated everything here :pray:

**Comment by m-Peter** [comment]
@SupunS Kind reminder :pray:

**Pull request closed without merging**
